### ISSUE TITLE
is PostGIS extension really needed?

### ISSUE THREAD

**Issue by gpongelli** [freol35241/ltss#15]
Hi freol,
I've found this HA component from its forum, thank you for this awesome job.

Now, is PostGIS really needed for your component ?
Does it work with only timescaledb?

I'm running HA on raspberry with docker and seems that there is no docker image for timescale+postgis, while there is a working docker image for timescaledb alone.

thanks.

**Comment by boesing** [comment]
@gpongelli There is [this addon](https://github.com/Expaso/hassos-addons) which I am using. 
Cannot make ltss run on 32-bit with the addon from `Expaso` as it was initially created for 64-bit but if you are on 64-bit already, this might work.
Until then, I've added a comment on https://github.com/Expaso/hassos-addon-timescaledb/issues/7. Probably that problem is fixable.

**Comment by gpongelli** [comment]
@boesing 
Hi Maximilian, thanks, I didn't know about that add-on.
I'm on a raspberry pi4, that's an armv7 arch.

I've installed a "clean" HA through [this docker image](https://hub.docker.com/r/homeassistant/raspberrypi4-homeassistant) (that's the [official one](https://www.home-assistant.io/docs/installation/docker/#raspberry-pi-34-raspberry-pi-os)); I've added the custom_components and the HACS, but no "Hass.io" there (or I'm confused with all those names).

Following your link I see that the "real" content is in [this repo](https://github.com/Expaso/hassos-addon-timescaledb) where [a Dockerfile](https://github.com/Expaso/hassos-addon-timescaledb/blob/master/timescaledb/Dockerfile) is found.

Going deeper on my HA installation, I see the "ltss" custom component that lands here, so maybe I've only to install it to see if it will build [that Dockerfile](https://github.com/Expaso/hassos-addon-timescaledb/blob/master/timescaledb/Dockerfile)... 

Do you know if it's possible to build (and how) [that Dockerfile](https://github.com/Expaso/hassos-addon-timescaledb/blob/master/timescaledb/Dockerfile) outside HA in a separate container ?
I mean, I would keep timescaledb+postgis docker container outside home assistant container, as I already have for influxdb and other db installation (I'm running plenty docker images from [SensorsIOT/IOTStack](https://github.com/sensorsiot/iotstack)).

Really thanks!

**Comment by boesing** [comment]
tbh, I dont know. 
I am just using it with supervisor and dont have deep knowledge with docker.

**Comment by freol35241** [comment]
@gpongelli 
Hi, for your first question. Yes, postgis is a required extension for ltss as of now. The reason for this is that ltss stores any positions from HA trackers in a proper GIS format making it possible to perform geographical queries.

Unfortunately I dont run this on a raspberry pi so I am no expert on available options, but her goes:

* I would give the addon suggested by @boesing another go. For any questions related to the addon, I suggest to try your luck with @Expaso who is the maintainer.
* Another option is to check out the docker image provided by @dekiesel here: https://github.com/dekiesel/arm7v32_timescaledb

Hope this helps!

**Comment by gpongelli** [comment]
Hi @freol35241 ,
Thanks for your answer!

I think I’ll try @dekiesel ‘s image first, trying to integrate ltss with it (maybe it’s needed only the folder into custom_components), just because it’s already built.

Then I could try removing its folder and building @boesing Add-on.

I hope only to have time to do all those things...

Coming back to ltss, to increase performance, is there any hope to convert and store sensor’s data as database’s datatype instead of json blob? (I cannot find discussion on home assistant forum regarding this)

Thanks

**Comment by freol35241** [comment]
@gpongelli 
since some months ago, ltss stores the attributes as [JSONB type](https://www.postgresql.org/docs/9.4/datatype-json.html) which is a binary representation of the json structure. In addition, ltss creates and index on this binary representation for further performance benefits.

This is **not** the same way as it is dealt with in the regular recorder component of HA (which uses an ordinary json text blob representation) that is referenced in the forum post you linked to.

I am closing this issue now since I believe you have answers to your initial questions, feel free to re-open of you disagree. For further questions specific to either of the two suggestions above, please open issues in the respective repositories instead.

**Comment by shouya** [comment]
Sorry to reply on a closed issue. I was thinking of the same when I'm trying to integrate ltss. I personally don't have any need to geolocation data so I also think installing the extension is gratuitous for my use cases. Especially now the official timescaledb docker image has ceased to provide postgis version (https://github.com/timescale/timescaledb-docker/commit/b737865a70c824dca0fc2e7f0ce5e1d1068c8743).

I understand geolocation is important for some people. So I hacked a bit in the code to remove dependency to PostGIS myself. Fortunately, the change was relatively small thanks to the author's clean code. I published my mod on https://github.com/shouya/ltss, which can be installed using hacs custom repo. I hope it helps to whoever thinking about the same thing.

@gpongelli
