### ISSUE TITLE
Feature request: "LITE" version setting - without Timescale and GIS, just pure PostgreSQL

### ISSUE THREAD

**Issue by freol35241** [freol35241/ltss#20]
Would be great to add something  like "LITE" version setting - without Timescale and GIS, just pure PostgreSQL. Already using your addon with some tweaked code to remove those unwanted dependecy plugins (commented few lines of code on DB creation). Thanks

_Originally posted by @rds76 in https://github.com/freol35241/ltss/issues/8#issuecomment-743063482_

**Comment by BenediktAllendorf** [comment]
What a coincidence! I'm just struggling with getting a simple timescaleDB + PostGIS docker image, which would be solved by this because I could just ignore PostGIS (I don't really need that).

I would be interested in helping with that.

Right now, I see two things that need to be adjusted:
1. Only create the configured extensions (either, both, none)
2. Handle `location` differently (e.g. don't save it at all? :D)

As far as I understand it, timescaledb only works "under the hood" right now - so it's faster but you can exchange it with pure Postgres without changing the code?

**Comment by freol35241** [comment]
Hi @BenediktAllendorf 
I would be very happy to review a PR for this so feel free to dig in! 

Some suggestions:
- please keep the current configuration as the default (i.e. with both extensions enabled
- without the postgis extension, location should probably just be stored in the regular attributes column (i.e. just skip the special treatment of it)
- this needs some proper documentation in the readme with clear info about which other config options that becomes superfluous etc when disabling for example the timescaledb extension
- i am expecting this to be a "first use only" option? So it should not be possible to add timescaledb to an existing setup initially without timescaledb (an example). This need to be very clear inte documentation!
