### ISSUE TITLE
Replace recorder component 

### ISSUE THREAD

**Issue by RubenKelevra** [freol35241/ltss#28]
Hey, really like the idea of using Postgre for storing the sensor data!

> This component is not to be considered as a replacement to the recorder component in Home Assistant but rather as an alternative to the InfluxDB component for more space-efficient long time storage of specific sensor states.

Is there a chance to extend the database to extend the recorder component completely in the future? I don't want two databases running just to store the same data and I'm sure Postgre is much faster with a lot of data compared to sqlite or MySQL.

**Comment by dekiesel** [comment]
@RubenKelevra Assuming I am understanding you right here: You can already use postgres as a database backend with home assistant:

https://www.home-assistant.io/integrations/recorder/

**Comment by RubenKelevra** [comment]
@dekiesel I was referring to the Readme which states:

> This component is not to be considered as a replacement to the recorder component in Home Assistant but rather as an alternative to the InfluxDB component for more space-efficient long time storage of specific sensor states.

**Comment by dekiesel** [comment]
I am probably not getting it, by why don't you use postgres with the recorder component? You can use ltss and the recorder with the same database (that's what I am doing).

**Comment by freol35241** [comment]
@RubenKelevra 
The main reason for the phrasing in the README is because it is "not possible" (read: would require quite a lot of work for not much gain) to just replace the recorder component in HA with another, custom one. And frankly, thats not really what LTSS aims to do anyway. While the recorder component is very tightly connected with the inner workings of HA and is used for all kinds of different things such as the logbook, the history view, persistence between restarts etc... LTSS just aims to do one thing which is provide fast and efficient storage for the timeseries data that is generated by your sensors connected to HA.

However, as @dekiesel has already pointed out, you can run also the recorder component with Postgresql as the backend. The main difference between using the recorder component with Postgresql in comparison with running LTSS can be summarized as follows:
* The recorder component uses “vanilla” Postgres whereas LTSS makes use of two extensions, TimescaleDB and PostGIS. TimescaleDB brings advanced timeseries handling/analytics functionality to Postgres and PostGIS enables GIS-powered data types and queries.
* The recorder component stores both HA states and HA events whereas LTSS stores only HA states, reducing the size of the database significantly.
* The recorder component stores state attributes as JSON-encoded text strings whereas LTSS makes use of the Postgres-specific JSONB type (a binary JSON representation) which increase performance and reduce database size further.
In general, the recorder component is well integrated with HA and should be your goto-choice if you only want to see your sensor readings from the last couple of weeks/months using Logbook/History Graph. LTSS is tuned for efficiently storing only state data (sensor readings) for long time periods (i.e. no purging of data after a couple of weeks/months) with better query performance and more advanced analytics functionality included.

Personally I run both the recorder component (using Postgres as a backend) with a short retention time (1 week) AND LTSS to make sure I keep my sensor readings “forever” in a space-efficient manner. And both of them use the same Postgresql instance, also as pointed out by @dekiesel.

**Comment by RubenKelevra** [comment]
@freol35241 interesting, thanks!

I thought it might be possible to create a target for the recorder and use TimescaleDB / PostGIS on the tables which would benefit in a transparent fashion for the recorder.

**Comment by freol35241** [comment]
@RubenKelevra Can I close this issue?

**Comment by RubenKelevra** [comment]
@freol35241 any closing words on me wondering why it isn't possible to transparently provide a database with Timescale as an backend?

Just out of curiosity :)

**Comment by freol35241** [comment]
Well, if you set up a postgresql + timescale instance and run the regular recorder component towards that one you will in essence "provide a database with Timescale as an backend", but since the recorder component does not "know" how to deal with timecale it wont make use of its full potential. If that is what you want, you will need to go ask the developers of the recorder component to either:
* Support it out of the box
* Provide a more modular database/storage structure in HA such that 3rd-party components like LTSS can be easily interfaced

Closing this now since I dont think I can provide any more insight into this, however, feel free to reopen it if you have further questions.
