### ISSUE TITLE
Feature: write all states, changed or not, regularly

### ISSUE THREAD

**Issue by laundmo** [freol35241/ltss#39]
First off: thanks for making this, I much prefer timescale to influx.

Currently, querying for rarely changing states in Grafana can be very painful, requiring giant queries such as: https://community.home-assistant.io/t/migrating-from-influxdb-to-timescaledb-on-a-raspberry-pi/235304/3

For setups where database size isn't really limited, it would be great to have an option to write all states every x minutes to a separate table. This table could exclude things like the JSONB column to save on a bit of data.

This would make Grafana visualizations much easier.

**Comment by pimw1** [comment]
Depending on your situation, you could do something similar as i did. In my specific case, no data respresents the functional value of 0.

If this does not work for you, i think it is better to create an issue for Grafana to ask for this feature. In the end, this is a limitation of Grafana. Repeating data points would be work-around and not tackling the root cause.

```
SELECT a.time,
a.metric,
SUM(a.value) AS value
FROM
(
SELECT
  $__timeGroupAlias("time",1m),
  entity_id AS metric,
  max(cast(state as numeric)) as value
FROM ltss
WHERE
  $__timeFilter("time") AND
  entity_id in ('sensor.gas_consumption_5m')
GROUP BY 1,2, $__timeGroup("time",'1m', 0)
UNION ALL
SELECT
  date_trunc('minute',((now())::timestamp ))as "time",
  'sensor.gas_consumption_5m' AS metric,
  0 as value
ORDER BY 1,2
) a
GROUP BY 1,2
```

**Comment by freol35241** [comment]
As already pointed out by @pimw1, this is really a limitation of Grafana and should not be handled by this kind of work around.
