### ISSUE TITLE
Having trubble finding my data from grafana and pgadmin

### ISSUE THREAD

**Issue by Coffee0297** [freol35241/ltss#83]
Hey, first of all thanks for this intergration, its super awsome for storing lots of data :)

I have used LTSS for a good part of a year, and now i finaly wanna see the logged data, but i have trubble finding it.
if i do a 
```
SELECT
  entity_id
FROM
  ltss
LIMIT
  500
```
 Then i only get some automation.xxx and i assume thats where every single sensor and so on shuld have been?
 The database is arround 8gb, so there shuld be something there :P

**Comment by freol35241** [comment]
Hi @Coffee0297, based on the info you have given so far, it is not very easy to give you any advice.

But, here comes my best guess: 

Your query will not give you 500 distinct (unique) entity_ids from the ltss table. It will return the 500 first results by the **default** ordering scheme of postgres since you have not explicitly given an ORDER BY clause. The default ordering is usually `ASC` (ascending) which for a text column means alphabetical ordering. My _guess_ is therefore that this is the reason you only see entities starting with `automation`.   

In general, when using LIMIT, its usually a good thing to also use  an ORDER BY clause so that you know what you can expect to be included in the limited rows you get back, see https://www.postgresql.org/docs/current/queries-limit.html. In your query, the ordering is using the default ordering which seems to have caused some confusion.

**Comment by Coffee0297** [comment]
Thank you! this was the ticket!!!! How is that not documented? Or am i just bad at searching?
Kind regards
